### ISSUE TITLE
还不能执行sql吗?

### ISSUE THREAD

**Issue by xiake999** [TeaMeow/Reiner#1]
@YamiOdymel  您好！  目前仅能构建sql语句，不能够执行吗？

**Comment by YamiOdymel** [comment]
天啊也太快有人找到了，因以為沒人看到所以先暫時休息開發，目前還沒完成，估計要兩三天

**Comment by xiake999** [comment]
@YamiOdymel  代码我基本上看完了，写的不错，打算在项目中使用了。

**Comment by YamiOdymel** [comment]
這項目還沒好怎麼就被關了

**Comment by xiake999** [comment]
我看代码已经提交了，所以就关闭了Comment
