### ISSUE TITLE
Goroutine 出错

### ISSUE THREAD

**Issue by xiake999** [TeaMeow/Reiner#2]
```
for i := 0; i < 10000; i++ {
		go func() {
			db.Copy(false).Table("Users").Insert(map[string]interface{}{
				"Username": "test",
				"Password": "test",
			})
}()
```

[mysql] 2017/07/04 14:34:07 packets.go:141: write tcp 127.0.0.1:51066->127.0.0.1:3306: wsasend: An existing connection w
as forcibly closed by the remote host.
[mysql] 2017/07/04 14:34:07 packets.go:141: write tcp 127.0.0.1:51068->127.0.0.1:3306: wsasend: An existing connection w
as forcibly closed by the remote host.
[mysql] 2017/07/04 14:34:07 packets.go:141: write tcp 127.0.0.1:50708->127.0.0.1:3306: wsasend: An existing connection w
as forcibly closed by the remote host.
[mysql] 2017/07/04 14:34:07 packets.go:141: write tcp 127.0.0.1:51069->127.0.0.1:3306: wsasend: An existing connection w
as forcibly closed by the remote host.
[mysql] 2017/07/04 14:34:07 packets.go:141: write tcp 127.0.0.1:51071->127.0.0.1:3306: wsasend: An existing connection w
as forcibly closed by the remote host.
[mysql] 2017/07/04 14:34:07 packets.go:141: write tcp 127.0.0.1:51072->127.0.0.1:3306: wsasend: An existing connection w
as forcibly closed by the remote host.
[mysql] 2017/07/04 14:34:07 packets.go:141: write tcp 127.0.0.1:51076->127.0.0.1:3306: wsasend: An existing connection w
as forcibly closed by the remote host.
[mysql] 2017/07/04 14:34:07 packets.go:141: write tcp 127.0.0.1:51077->127.0.0.1:3306: wsasend: An existing connection w
as forcibly closed by the remote host.
[mysql] 2017/07/04 14:34:07 packets.go:141: write tcp 127.0.0.1:51078->127.0.0.1:3306: wsasend: An existing connection w
as forcibly closed by the remote host.
[mysql] 2017/07/04 14:34:07 packets.go:141: write tcp 127.0.0.1:51081->127.0.0.1:3306: wsasend: An existing connection w
as forcibly closed by the remote host.
[mysql] 2017/07/04 14:34:07 packets.go:141: write tcp 127.0.0.1:51079->127.0.0.1:3306: wsasend: An existing connection w
as forcibly closed by the remote host.
[mysql] 2017/07/04 14:34:07 packets.go:141: write tcp 127.0.0.1:51083->127.0.0.1:3306: wsasend: An existing connection w
as forcibly closed by the remote host.

**Comment by YamiOdymel** [comment]
我還在處理最後的 Thread Safe 部分，感覺有點小麻煩

**Comment by xiake999** [comment]
@YamiOdymel 辛苦了。

**Comment by YamiOdymel** [comment]
你貼出的這個問題應該是你伺服器的問題，我這裡測試相同的程式碼沒有問題，你可能需要檢查一下你那邊的連線。

整個專案已經 95% 完成了，只差 Thread Safe 跟 Transaction（Rollback／Commit）我還沒有寫好測試

**Comment by YamiOdymel** [comment]
如果你那邊設置好沒問題之後遇到  

```
connection reset by peer
```

類似的問題，是因為 MySQL 的連線數設置過低（我這邊預設是 `151`），導致多個連線被切斷，試著輸入

```
SHOW VARIABLES LIKE "max_connections"
```

查看允許最高的同時連線數，然後你可以透過

```
SET GLOBAL max_connections = 5000;
```

更改這個設定，這樣就不會出現 `connection reset by peer` 錯誤了。

**Comment by xiake999** [comment]
@YamiOdymel  是我这边数据服务器出现的问题,已经解决了，谢谢
