### ISSUE TITLE
migration 支持constraint

### ISSUE THREAD

**Issue by xiake999** [TeaMeow/Reiner#3]
您好! 是否可以考虑支持constraint?
```
KEY `FK_Reference_1` (`create_user_id`),
CONSTRAINT `FK_Reference_1` FOREIGN KEY (`create_user_id`) REFERENCES `sys_user` (`user_id`)
```

**Comment by YamiOdymel** [comment]
當初在替 Migration 做 FK 功能的時候想了這個想很久，想不出來有 `CONSTRAINT` 跟沒有 `CONSTRAINT` 的差異，能請你解釋一下？

**Comment by YamiOdymel** [comment]
我好像自己看出來了，當使用 Constraint 的時候，整個資料庫（Database）不能有相同的 Key Name，這個功能貌似可以用在 Index、Foreign、Primary、Unique Keys，要想一下怎麼設計了

**Comment by xiake999** [comment]
防止不合法的数据写入数据库,开发人员可以定义完整性规则,增强商业规则,限制数据表中的数据. 我个人的理解。

**Comment by YamiOdymel** [comment]
@xiake999 既然如此，你為什麼不用

```go
.Foreign("FK_Reference_1", []string{"create_user_id"}, []string{"sys_user.user_id"})
```

```sql
FOREIGN KEY `FK_Reference_1` (`create_user_id`) REFERENCES `sys_user` (`user_id`)
```

代替

```sql
CONSTRAINT `FK_Reference_1` FOREIGN KEY (`create_user_id`) REFERENCES `sys_user` (`user_id`)
```

這兩者有差異嗎？我開始對我剛才的認知產生懷疑了

**Comment by YamiOdymel** [comment]
好，我現在大概知道是怎麼回事了，Migration 本身支援 Foreign Key（這應該是你原先的問題？），我以為你指的是能不能新增 `CONSTRAINT` 關鍵字。

現在查到了 `CONSTRAINT` 是用在 `ALTER TABLE` 時所需的關鍵字，一般在 `CREATE TABLE` 的時候可以不需要（有跟沒有的功能是一樣的）。

**Comment by xiake999** [comment]
谢谢,我查阅了资料,似乎没有任何不同之处。
[http://www.fooish.com/sql/foreign-key-constraint.html ](http://www.fooish.com/sql/foreign-key-constraint.html )
